# Generated by Django 4.2.16 on 2024-11-18 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='名称', max_length=64)),
                ('text', models.TextField(help_text='文本', max_length=64)),
                ('mark', models.TextField(help_text='备注', max_length=64)),
                ('lontitude', models.FloatField(blank=True, help_text='经度', null=True)),
                ('latitude', models.FloatField(blank=True, help_text='纬度', null=True)),
                ('is_passed', models.BooleanField(default=False, help_text='是否途径点')),
                ('create', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间')),
                ('update', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('marker_image', models.URLField(blank=True, help_text='图标 URL', null=True)),
            ],
            options={
                'verbose_name': '地点信息',
                'verbose_name_plural': '地点信息',
            },
        ),
        migrations.CreateModel(
            name='MarkerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_image', models.URLField(help_text='普通图标')),
                ('passed_image', models.URLField(help_text='途径图标')),
                ('create', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间')),
                ('update', models.DateTimeField(auto_now=True, help_text='更新时间')),
            ],
            options={
                'verbose_name': 'Marker图标',
                'verbose_name_plural': 'Marker图标',
            },
        ),
    ]
