# Generated by Django 3.2.3 on 2024-11-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FootPrint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='note',
            field=models.TextField(blank=True, help_text='笔记', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='picture_url',
            field=models.URLField(blank=True, help_text='图片 URL', null=True),
        ),
    ]
