# Generated by Django 3.2.3 on 2024-11-19 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FootPrint', '0003_location_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='leave_date',
            field=models.DateField(blank=True, help_text='离开日期', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='visit_date',
            field=models.DateField(blank=True, help_text='访问日期', null=True),
        ),
    ]
