# Generated by Django 3.2.3 on 2024-11-19 07:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FootPrint', '0004_auto_20241119_0329'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_type', models.IntegerField(default=1, help_text='地图类型：1 标准地图 2 地球模式 3 普通卫星地图')),
                ('map_zoom', models.IntegerField(default=15, help_text='地图缩放')),
                ('center_latitude', models.FloatField(blank=True, help_text='中心纬度', null=True)),
                ('center_longitude', models.FloatField(blank=True, help_text='中心经度', null=True)),
                ('is_enable_scroll_wheel_zoom', models.BooleanField(default=True, help_text='是否启用滚轮缩放')),
                ('is_add_control', models.BooleanField(default=True, help_text='是否添加缩放控件')),
                ('is_add_scaleCtrl', models.BooleanField(default=True, help_text='是否添加比例尺控件')),
                ('create', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间')),
                ('update', models.DateTimeField(auto_now=True, help_text='更新时间')),
            ],
            options={
                'verbose_name': '地图配置',
                'verbose_name_plural': '地图配置',
            },
        ),
    ]
