# Generated by Django 3.2.3 on 2024-11-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FootPrint', '0007_auto_20241119_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='markerimage',
            name='blog_url',
            field=models.URLField(default='https://oba.by/', help_text='默认连接'),
        ),
    ]
