# Generated by Django 3.2.3 on 2024-11-20 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FootPrint', '0009_auto_20241120_0648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapsetting',
            old_name='is_enabel_3d',
            new_name='is_enable_3d',
        ),
    ]
