# Generated by Django 3.2.3 on 2024-11-20 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FootPrint', '0010_rename_is_enabel_3d_mapsetting_is_enable_3d'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_key', models.CharField(help_text='地图 key', max_length=64)),
                ('create', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间')),
                ('update', models.DateTimeField(auto_now=True, help_text='更新时间')),
            ],
            options={
                'verbose_name': '地图Key',
                'verbose_name_plural': '地图Key',
            },
        ),
    ]
