# Generated by Django 3.2.3 on 2024-12-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FootPrint', '0011_mapkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapkey',
            name='server_key',
            field=models.CharField(blank=True, help_text='服务端 key', max_length=64, null=True),
        ),
    ]
